sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/3569d7edff0d38f93cd7"
    on_success: change
    on_failure: always
    on_start: false
